name: Publish Test Results

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions: {}

jobs:
  test-results:
    name: Publish Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write
      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: artifacts/test-results/test-results.json
          time_unit: milliseconds
          comment_mode: "off"
